### ISSUE TITLE
Android Basics: Amphibians app--------Error in GENERATED SOURCE FILE

### ISSUE THREAD

**Issue by jh115424** [google-developer-training/android-basics-kotlin-amphibians-app#1]
there is a error in DataBinderMapperImpL

Nothing was touched.    It says these files should not be edited, yet you guys have a error in it.     How can it be fixed if it can't be edited from a mistake you guys made when you built it?

it is the first line underlined in red.

PLEASE TELL ME HOW TO FIX IT.

screen shot below....

<img width="1440" alt="Screen Shot 2022-02-16 at 7 39 54 AM" src="https://user-images.githubusercontent.com/91148652/154277427-cdead22e-5d8e-49ee-a62d-5cc13dcb899f.png">

**Comment by wrbyepct** [comment]
Having the same problem, spent the entire afternoon still no clues...
Have you solved it?

**Comment by jh115424** [comment]
Nah, I'm gonna come back to it, delete the project and start from scratch.   I'm doing the Lunchtray app and so far, so good 👍

 I will let you know when I do though and what the results are.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jimmy-2** [comment]
Hello. Not sure if you still have a problem but it is also underlined red with errors for me. However I don't think it is a problem because I am able to build and run the starter app. Even after I finished the project and ran the tests successfully, the file still shows a red underline. I noticed this in other projects too with generated databindermapper files.

**Comment by Wavey1287** [comment]
@OwenScott-GDS - this is still an issue.

**Comment by Mahmoud-Ibrahim-750** [comment]
Check this out #16, it may help.

**Comment by jh115424** [comment]
thx!


Jennifer Hodge

Service BDC

414-329-5800

Russ Darrow Honda


[cid:ef579635-e4f8-4909-845f-228bdda7b71e]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by Mahmoud-Ibrahim-750** [comment]
@jh115424 did it work for you?

**Comment by jh115424** [comment]
it did yes, thanks!


Jennifer Hodge

Service BDC

414-329-5800

Russ Darrow Honda


[cid:6743d402-f7f0-4e10-b5aa-6999d1721049]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by Mahmoud-Ibrahim-750** [comment]
Great!
Happy learning journey.
