### ISSUE TITLE
Android Basics: Amphibians app

### ISSUE THREAD

**Issue by naveenmittal04** [google-developer-training/android-basics-kotlin-amphibians-app#12]
https://developer.android.com/codelabs/basic-android-kotlin-training-project-amphibians?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-amphibians#3

This page displays Lemonade app test instead of Amphibians Test.

**Comment by kdannothere** [comment]
No.
