### ISSUE TITLE
Android Basics: Amphibians app-----ViewModelCode does not even exist!

### ISSUE THREAD

**Issue by jh115424** [google-developer-training/android-basics-kotlin-amphibians-app#2]
in Get Started section, you are telling me to launch a coroutine using ViewModelScope, yet when I do it, it is red and I can't import it.

How am I supposed to do it then?

2 screen shots below....

<img width="1440" alt="Screen Shot 2022-02-16 at 8 10 56 AM" src="https://user-images.githubusercontent.com/91148652/154282266-da095d15-0ab0-4235-8dec-709fc5a96f91.png">

<img width="1440" alt="Screen Shot 2022-02-16 at 8 13 02 AM" src="https://user-images.githubusercontent.com/91148652/154282327-3e95c353-54d6-4b08-bc86-7fb8275c298d.png">

**Comment by redeveloper3** [comment]
Hi there - I'm working on this project too at the moment.  My import list for AmphibianViewModel.kt is

```
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.amphibians.network.Amphibian
import com.example.amphibians.network.AmphibianApi
import kotlinx.coroutines.launch
```

Also it looks like the '**viewModelScope**' needs a lower case 'v', it displays red when using upper case.
I hope this helps.

**Comment by jh115424** [comment]
It did thanks!

Now, when I typed the viewModelScope in the imports section,  it was grayed out.

What does that mean?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jh115424** [comment]
Oh darn, I thought it worked but it's still red even lower case and after I put it in the imports section. And even then, that sentence is grayed out. I don't get it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by redeveloper3** [comment]
Can I check if you also changed the 'ViewModelScope' to 'viewModelScope' in the function getAmphibianList() ?

i.e.
`viewModelScope.launch{ ...etc`

If the import line is greyed out it means it's not used within the code, so at a guess that could be it....

**Comment by jh115424** [comment]
but it what they said to put in Android Studio.    Thats the thing.   So how can it be both?


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:76d5f945-be0d-49b3-a3b8-28f8ec0f5105]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
here is a screen shot ...

as you see it shows as a variable but for some reason in the second screen shot it is still red!

it should not be if it is a variable.




Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:0c963f15-fbc1-42f0-b6e7-f244436d742a]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
_status also come up as red with no way to import.


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:e4a647bd-92d9-436b-ad49-15e98db517cf]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
ok....this is what I have so far?

Please tell me why so much red?

I have been stuck on this part for 2 days now.   Do you have the code for it so I can study it and move on, or do you know how I can unred what you see?

screenshot included

PLEASE!


thanks


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:e7532cb2-dfcf-4364-8c0b-f2bcae74e4ea]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by redeveloper3** [comment]
Could you please re-post the screenshot as it doesn't seem to have uploaded - thanks.

**Comment by jh115424** [comment]
ok, do you see it now?





Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:599bc70f-c050-4a63-b06d-ccbe4035a9eb]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by redeveloper3** [comment]
I can only see screenshots in your first post, could you try pasting the code into the message & highlighting the red items in bold - thanks.

**Comment by jh115424** [comment]
what about now?


[cid:8593f19f-c816-4596-bd37-2579cf3b200b]


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:4ee90f26-c2ef-4878-9eeb-29f6ee1fc507]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by kalactor** [comment]
hello guys, i have completed this project and uploaded the completed project to my GitHub
check this out https://github.com/kalactor/android-basics-kotlin-amphibians-app
