### ISSUE TITLE
Android Basics: Amphibians app

### ISSUE THREAD

**Issue by MikeWight** [google-developer-training/android-basics-kotlin-amphibians-app#5]
When I use Base URL: https://developer.android.com/courses/pathways/android-basics-kotlin-unit-4-pathway-2/ for retrofit (which is provided in the codelab) , I get 404. I can hit the json directly though (https://developer.android.com/courses/pathways/android-basics-kotlin-unit-4-pathway-2/android-basics-kotlin-unit-4-pathway-2-project-api.json). I'll double check my code to see what's up

**Comment by VKostenc** [comment]
Works fine if you will split the URL like this ->
```
private const val BASE_URL =
    "https://developer.android.com/courses/pathways/android-basics-kotlin-unit-4-pathway-2/"

@GET("android-basics-kotlin-unit-4-pathway-2-project-api.json")
```

Also if someone will face an issue with Manifest merging - add `android:exported="true"` to the Manifest and try to use the latest version of `androidx.fragment:fragment-testing`. At least 1.4.1.
`androidx.fragment:fragment-testing:1.4.1`
