### ISSUE TITLE
Android Basics: Amphibians app , can not call the getAmphibianList() method

### ISSUE THREAD

**Issue by Weaam87** [google-developer-training/android-basics-kotlin-amphibians-app#6]
In **update the UI from the ViewModel** , step 1 , we can not call the **getAmphibianList()** method from the **ViewModel** in **AmphibianListFragment** because it is a private method , it's better to add **init {getAmphibianList()}** in the AmphibianViewModel

**Comment by patricioconti** [comment]
Great solution! Thank you!
